"""Customer view of the cleaned Online Retail sales.

Covers identified customers only (guest checkouts have no CustomerID). Reads
data/clean/sales.csv and data/clean/returns.csv (run clean_data.py first) and
writes charts to results/charts/ plus the numbers to results/customer_summary.md.

Revenue is net of product returns, the same definition as eda.py.
"""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import pandas as pd

from eda import BLUE, CHART_DIR, GREY, LAST_FULL_MONTH, RESULTS_DIR, fmt, gbp, load


def customer_table(sales, returns):
    known = sales[~sales["IsGuest"]]
    cust = known.groupby("CustomerID").agg(
        gross=("Revenue", "sum"), orders=("InvoiceNo", "nunique"),
        first=("InvoiceDate", "min"), last=("InvoiceDate", "max"),
        country=("Country", "first"))
    cust["returns"] = returns.groupby("CustomerID")["Revenue"].sum()
    cust["returns"] = cust["returns"].fillna(0)
    cust["net"] = cust["gross"] + cust["returns"]
    return cust.sort_values("net", ascending=False)


def pareto(cust):
    net = cust["net"].clip(lower=0).sort_values(ascending=False)
    cum = net.cumsum() / net.sum()
    pct_cust = pd.Series(range(1, len(net) + 1), index=net.index) / len(net)
    return pct_cust.values, cum.values


def share_of_top(cust, frac):
    net = cust["net"].clip(lower=0).sort_values(ascending=False)
    return net.head(round(len(net) * frac)).sum() / net.sum()


def chart_pareto(cust):
    x, y = pareto(cust)
    top20 = share_of_top(cust, 0.20)
    fig, ax = plt.subplots(figsize=(7, 4.5))
    ax.plot(x, y, color=BLUE, lw=2)
    ax.plot([0, 1], [0, 1], color=GREY, ls="--", lw=1, label="Equal spend")
    ax.axvline(0.2, color=GREY, lw=0.8)
    ax.annotate(f"Top 20% of customers\n= {top20:.0%} of net revenue",
                xy=(0.2, top20), xytext=(0.32, top20 - 0.2),
                arrowprops=dict(arrowstyle="->", color="black"))
    ax.xaxis.set_major_formatter(mtick.PercentFormatter(1.0))
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0))
    ax.set_xlabel("Share of identified customers (ranked by net spend)")
    ax.set_ylabel("Cumulative share of net revenue")
    ax.set_title("Customer concentration (Pareto curve)")
    ax.legend(frameon=False, loc="lower right")
    fig.tight_layout()
    fig.savefig(CHART_DIR / "05_customer_pareto.png")
    plt.close(fig)


def new_vs_returning(sales, cust):
    known = sales[~sales["IsGuest"]].copy()
    first_month = cust["first"].dt.to_period("M").astype(str)
    known["cohort"] = known["CustomerID"].map(first_month)
    known["type"] = (known["cohort"] == known["InvoiceMonth"]).map(
        {True: "new", False: "returning"})
    m = known.pivot_table(index="InvoiceMonth", columns="type",
                          values="Revenue", aggfunc="sum").fillna(0)
    m["returning_share"] = m["returning"] / (m["new"] + m["returning"])
    return m


def chart_new_vs_returning(m):
    full = m.loc["2011-01":LAST_FULL_MONTH]  # Dec 2010 has no history to be "returning"
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.bar(full.index, full["returning"], color=BLUE, label="Returning customers")
    ax.bar(full.index, full["new"], bottom=full["returning"], color=GREY,
           label="New customers (first order that month)")
    ax.yaxis.set_major_formatter(gbp)
    ax.set_title("Gross revenue from new vs returning customers (identified only)")
    ax.tick_params(axis="x", rotation=45)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(CHART_DIR / "06_new_vs_returning.png")
    plt.close(fig)


def main():
    CHART_DIR.mkdir(parents=True, exist_ok=True)
    sales, returns = load()
    cust = customer_table(sales, returns)
    chart_pareto(cust)
    m = new_vs_returning(sales, cust)
    chart_new_vs_returning(m)

    n = len(cust)
    repeat = (cust["orders"] >= 2).mean()
    one_off = cust[cust["orders"] == 1]
    end = sales["InvoiceDate"].max()
    # customers whose first order was before Jun 2011 had 6+ months to come back
    early = cust[cust["first"] < "2011-06-01"]
    lapsed = early[(end - early["last"]).dt.days > 90]
    top10 = cust.head(10).copy()
    top10["share"] = top10["net"] / cust["net"].clip(lower=0).sum()
    full = m.loc["2011-01":LAST_FULL_MONTH]

    lines = [
        "# Customer summary (generated by scripts/customers.py)",
        "",
        "Identified customers only; revenue net of product returns.",
        "",
        "## Headline",
        f"- Identified customers: {n:,}",
        f"- Repeat customers (2+ orders): {repeat:.1%}",
        f"- One-order customers: {len(one_off):,} ({len(one_off) / n:.1%}), "
        f"£{one_off['net'].sum():,.0f} net ({one_off['net'].sum() / cust['net'].sum():.1%})",
        f"- Median orders per customer: {cust['orders'].median():.0f}; "
        f"median net spend: £{cust['net'].median():,.0f}",
        f"- Top 1% of customers: {share_of_top(cust, 0.01):.1%} of net revenue",
        f"- Top 10% of customers: {share_of_top(cust, 0.10):.1%} of net revenue",
        f"- Top 20% of customers: {share_of_top(cust, 0.20):.1%} of net revenue",
        f"- Bottom 50% of customers: {1 - share_of_top(cust, 0.50):.1%} of net revenue",
        f"- Customers with net spend ≤ £0 (returned everything): {(cust['net'] <= 0).sum()}",
        f"- Returning-customer share of gross revenue, Jan–Nov 2011: "
        f"{full['returning'].sum() / (full['new'] + full['returning']).sum():.1%} "
        f"(lowest {full['returning_share'].min():.1%} in {full['returning_share'].idxmin()}, "
        f"highest {full['returning_share'].max():.1%} in {full['returning_share'].idxmax()})",
        f"- Customers acquired before Jun 2011: {len(early):,}; of these, "
        f"{len(lapsed):,} ({len(lapsed) / len(early):.1%}) had not ordered in the last 90 days "
        f"before {end:%Y-%m-%d}, £{lapsed['net'].sum():,.0f} lifetime net",
        "",
        "## Top 10 customers by net revenue",
        fmt(top10[["country", "orders", "gross", "returns", "net", "share"]],
            money=("gross", "returns", "net"), pct=("share",)),
        "",
        "## New vs returning gross revenue by month",
        fmt(m, money=("new", "returning"), pct=("returning_share",)),
        "",
    ]
    (RESULTS_DIR / "customer_summary.md").write_text("\n".join(lines))
    print("\n".join(lines[:18]))


if __name__ == "__main__":
    main()
